# Site Info
title:              "Self-Supervisor"
description:        "Self-Supervisor"
author_name:        "Augustine Mavor-Parker" # change this to your name
logo_url:           /the-plain-academic/assets/graduation.jpg # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://self-supervisor.github.io # main url
baseurl:            /self-supervisor
permalink:          /:title # Post permalink
timezone:           America/Recife # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap
collections:
  projects:
    output: true
    permalink: /projects/:name

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      type:         "projects"
    values:
      layout:       "post"
